import Head from 'next/head'
import Header from '@/components/Header/Header'

import { Inter } from 'next/font/google'
import { populateToLocalStorage } from '@/utils/populateQuestions'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Peerprep Questions Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {populateToLocalStorage()}
      </main>
    </>
  )
}
