import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import QuestionsTable from '@/components/Questions/QuestionsTable/QuestionsTable'

export default function Home() {
  return (
    <>
      <Head>
        <title>PeerPrep Questions Bank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <QuestionsTable />
        </Layout>
      </main>
    </>
  )
}
