FROM node:18

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

ENV PORT=3002
ENV NODE_ENV=production
ENV JSON_WEB_TOKEN_SECRET=MkyAu6gLS5qRDDRczHbqoH44YfJk8TYTnWq3f/kCszdH60kbTrJWjw==
ENV QUESTION_SERVICE_URI=https://question-service-wlcbbioyfq-de.a.run.app
ENV FRONTEND_URI=https://frontend-wlcbbioyfq-de.a.run.app
EXPOSE 3002
CMD ["npm", "start"]
